# Numpy : package for multidimensional array 

In [ ]:
import numpy as np 

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [ ]:
sample_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Create an array of zeros with 2 rows and 10 columns 

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(3,2)


array([[0.16214687, 0.98354896],
       [0.13799409, 0.10496072],
       [0.87633178, 0.6752686 ]])

In [ ]:
np.random.randn(3,2)

array([[ 0.63522623,  1.33736481],
       [-0.93766756, -0.91119938],
       [ 3.57556421, -1.19349196]])

In [ ]:
np.random.randint(1,5)

1

In [ ]:
np.random.randint(34,100,50)

array([84, 85, 87, 60, 89, 63, 69, 55, 51, 82, 63, 47, 66, 64, 39, 74, 63,
       62, 43, 73, 69, 73, 48, 38, 40, 41, 50, 55, 41, 42, 62, 80, 59, 63,
       99, 44, 47, 67, 49, 40, 93, 41, 73, 65, 98, 74, 55, 47, 56, 99])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
 rand_array=np.random.randint(0,100,20)
 rand_array

array([51, 57, 33, 92, 30, 50,  8, 20, 45, 28,  2, 90, 64, 51, 96, 77, 43,
       85, 14, 35])

In [ ]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

2

In [ ]:
rand_array.argmin()

10

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.29525942, 0.87921795, 0.43855713],
       [0.06748512, 0.64569761, 0.68104019]])

In [ ]:
a.T

array([[0.29525942, 0.06748512],
       [0.87921795, 0.64569761],
       [0.43855713, 0.68104019]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

13

In [ ]:
sample_array[3:7]

array([13, 14, 15, 16])

In [ ]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [ ]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two Dimensional Array

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [ ]:
sample_matrix[0:2,2]

array([ 1, 21])

In [ ]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [ ]:
sample_matrix[2]

array([56, 76, 24,  7])

In [ ]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [ ]:
sample_array=np.arange(1,20)

In [ ]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.max(sample_array)

19

In [ ]:
np.min(sample_array)

1

In [ ]:
np.argmax(sample_array)

18

In [ ]:
np.argmin(sample_array)

0

In [ ]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
np.std(sample_array)

5.477225575051661

In [ ]:
np.var(sample_array)

30.0

In [ ]:
np.mean(sample_array)

10.0

In [ ]:
array=np.random.randn(3,4)
array

array([[-0.31850126,  0.61359899,  0.70077857, -2.63263315],
       [ 0.48217376, -1.77261809, -0.53176402, -2.15500121],
       [ 0.25522323, -0.24016601, -1.30765186,  1.07294846]])

In [ ]:
np.round(array,decimals=3)

array([[-0.319,  0.614,  0.701, -2.633],
       [ 0.482, -1.773, -0.532, -2.155],
       [ 0.255, -0.24 , -1.308,  1.073]])

In [ ]:
sports=np.array(["golf","cricket","fball","cricket","fabll","basketball"])
np.unique(sports)

array(['basketball', 'cricket', 'fabll', 'fball', 'golf'], dtype='<U10')

### Pandas 

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/CardioGoodFitness-1.csv")

In [ ]:
df.head(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
0   TM195   18    Male         14        Single      3        4   29562    112
1   TM195   19    Male         15        Single      2        3   31836     75
2   TM195   19  Female         14     Partnered      4        3   30699     66
3   TM195   19    Male         12        Single      3        3   32973     85
4   TM195   20    Male         13     Partnered      4        2   35247     47
5   TM195   20  Female         14     Partnered      3        3   32973     66
6   TM195   21  Female         14     Partnered      3        3   35247     75
7   TM195   21    Male         13        Single      3        3   32973     85
8   TM195   21    Male         15        Single      5        4   35247    141
9   TM195   21  Female         15     Partnered      2        3   37521     85

In [ ]:
df.tail(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
170   TM798   31    Male         16     Partnered      6        5   89641   
171   TM798   33  Female         18     Partnered      4        5   95866   
172   TM798   34    Male         16        Single      5        5   92131   
173   TM798   35    Male         16     Partnered      4        5   92131   
174   TM798   38    Male         18     Partnered      5        5  104581   
175   TM798   40    Male         21        Single      6        5   83416   
176   TM798   42    Male         18        Single      5        4   89641   
177   TM798   45    Male         16        Single      5        5   90886   
178   TM798   47    Male         18     Partnered      4        5  104581   
179   TM798   48    Male         18     Partnered      4        5   95508   

     Miles  
170    260  
171    200  
172    150  
173    360  
174    150  
175    200  
176    200  
177    160  
178    120  
179    180

In [ ]:
df.sample()

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  Miles
2   TM195   19  Female         14     Partnered      4        3   30699     66

In [ ]:
df.sample(10)

Product  Age  Gender  Education MaritalStatus  Usage  Fitness  Income  \
118   TM498   32    Male         16        Single      4        3   60261   
59    TM195   33  Female         16        Single      2        2   55713   
26    TM195   24  Female         16        Single      4        3   46617   
63    TM195   35    Male         16     Partnered      4        3   48891   
32    TM195   25  Female         16     Partnered      2        2   40932   
51    TM195   29  Female         14     Partnered      2        2   46617   
13    TM195   22  Female         14        Single      3        3   35247   
52    TM195   29  Female         16     Partnered      4        3   50028   
55    TM195   31    Male         14     Partnered      2        2   54576   
146   TM798   24    Male         16        Single      4        5   61006   

     Miles  
118    127  
59      38  
26      75  
63      85  
32      47  
51      38  
13      75  
52      94  
55      47  
146    100

In [ ]:
df.shape

(180, 9)

In [ ]:
df.dtypes

Product          object
Age               int64
Gender           object
Education         int64
MaritalStatus    object
Usage             int64
Fitness           int64
Income            int64
Miles             int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Product        180 non-null    object
 1   Age            180 non-null    int64 
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64 
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64 
 6   Fitness        180 non-null    int64 
 7   Income         180 non-null    int64 
 8   Miles          180 non-null    int64 
dtypes: int64(6), object(3)
memory usage: 12.8+ KB


In [ ]:
df.isnull().sum()

Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64

In [ ]:
df.describe()

Age   Education       Usage     Fitness         Income  \
count  180.000000  180.000000  180.000000  180.000000     180.000000   
mean    28.788889   15.572222    3.455556    3.311111   53719.577778   
std      6.943498    1.617055    1.084797    0.958869   16506.684226   
min     18.000000   12.000000    2.000000    1.000000   29562.000000   
25%     24.000000   14.000000    3.000000    3.000000   44058.750000   
50%     26.000000   16.000000    3.000000    3.000000   50596.500000   
75%     33.000000   16.000000    4.000000    4.000000   58668.000000   
max     50.000000   21.000000    7.000000    5.000000  104581.000000   

            Miles  
count  180.000000  
mean   103.194444  
std     51.863605  
min     21.000000  
25%     66.000000  
50%     94.000000  
75%    114.750000  
max    360.000000

In [ ]:
df.describe(include="all")  

Product         Age Gender   Education MaritalStatus       Usage  \
count      180  180.000000    180  180.000000           180  180.000000   
unique       3         NaN      2         NaN             2         NaN   
top      TM195         NaN   Male         NaN     Partnered         NaN   
freq        80         NaN    104         NaN           107         NaN   
mean       NaN   28.788889    NaN   15.572222           NaN    3.455556   
std        NaN    6.943498    NaN    1.617055           NaN    1.084797   
min        NaN   18.000000    NaN   12.000000           NaN    2.000000   
25%        NaN   24.000000    NaN   14.000000           NaN    3.000000   
50%        NaN   26.000000    NaN   16.000000           NaN    3.000000   
75%        NaN   33.000000    NaN   16.000000           NaN    4.000000   
max        NaN   50.000000    NaN   21.000000           NaN    7.000000   

           Fitness         Income       Miles  
count   180.000000     180.000000  180.000000  
unique         NaN            NaN         NaN  
top            NaN            NaN         NaN  
freq           NaN            NaN         NaN  
mean      3.311111   53719.577778  103.194444  
std       0.958869   16506.684226   51.863605  
min       1.000000   29562.000000   21.000000  
25%       3.000000   44058.750000   66.000000  
50%       3.000000   50596.500000   94.000000  
75%       4.000000   58668.000000  114.750000  
max       5.000000  104581.000000  360.000000

In [ ]:
### Pandas -> To create data , create table , manipulation

In [1]:
import pandas as pd
import numpy as np

In [6]:
labels=['w','x','y','z']
sample_lists=[100,200,300,400]
array=np.array([1,2,3,4])
dict={'w':10,'x':20,'y':30,'z':40}

In [8]:
pd.Series(data=sample_lists)

0    100
1    200
2    300
3    400
dtype: int64

In [9]:
pd.Series(data=sample_lists,index=labels)

w    100
x    200
y    300
z    400
dtype: int64

In [10]:
pd.Series(sample_lists,array)

1    100
2    200
3    300
4    400
dtype: int64

In [11]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [16]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [17]:
sports1['cricket']

1

In [22]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [23]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [24]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.661219  0.446334  0.897713  0.954300  0.627852
B  0.984527  0.407571  0.286460  0.075602  0.445947
C  0.521136  0.140050  0.281462  0.135698  0.239824
D  0.683549  0.349967  0.418521  0.336395  0.935201
E  0.659006  0.498624  0.252121  0.177879  0.812309
F  0.959916  0.398795  0.834234  0.782774  0.954811
G  0.095736  0.953745  0.274696  0.597623  0.437618
H  0.651485  0.212977  0.037526  0.839866  0.831330

In [25]:
df1["Score3"]

A    0.897713
B    0.286460
C    0.281462
D    0.418521
E    0.252121
F    0.834234
G    0.274696
H    0.037526
Name: Score3, dtype: float64

In [27]:
 df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.661219  0.446334  0.897713
B  0.984527  0.407571  0.286460
C  0.521136  0.140050  0.281462
D  0.683549  0.349967  0.418521
E  0.659006  0.498624  0.252121
F  0.959916  0.398795  0.834234
G  0.095736  0.953745  0.274696
H  0.651485  0.212977  0.037526

In [28]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.661219  0.446334  0.897713  0.954300  0.627852  1.107553
B  0.984527  0.407571  0.286460  0.075602  0.445947  1.392099
C  0.521136  0.140050  0.281462  0.135698  0.239824  0.661186
D  0.683549  0.349967  0.418521  0.336395  0.935201  1.033516
E  0.659006  0.498624  0.252121  0.177879  0.812309  1.157630
F  0.959916  0.398795  0.834234  0.782774  0.954811  1.358711
G  0.095736  0.953745  0.274696  0.597623  0.437618  1.049481
H  0.651485  0.212977  0.037526  0.839866  0.831330  0.864462

In [33]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [36]:
df['ID']

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [38]:
df[["ID","Name"]]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [50]:
df=df.drop("ID",axis=1)

KeyError: ignored

In [47]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123

In [48]:
df.drop(2,axis=0)

Name  Profit
0   John      20
1  Mercy      54
3  Kavin      87
4  Lally     123